FROM registry.access.redhat.com/ubi8/python-311:1-91.1747789949@sha256:622f604b360182bad6d0267e78525e275d924ea5b56b673731df2434fbfec9f0

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# modify permissions to support running with a random uid
RUN chmod g+w $(python -c "import feast.ui as ui; print(ui.__path__)" | tr -d "[']")/build/projects-list.json